# Generated by Django 2.1.4 on 2018-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Номер телефону')),
                ('instagram', models.CharField(blank=True, max_length=32, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=32, verbose_name='Facebook')),
                ('skype', models.CharField(blank=True, max_length=32, verbose_name='Skype')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Tastes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_type', models.CharField(max_length=32)),
                ('available', models.BooleanField(default=True, verbose_name='Доступність')),
            ],
            options={
                'verbose_name': 'Смак',
                'verbose_name_plural': 'Смаки',
            },
        ),
    ]
